RegMap = {
    'NEVER': 'eve.NEVER',
    'LESS': 'eve.LESS',
    'LEQUAL': 'eve.LEQUAL',
    'GREATER': 'eve.GREATER',
    'GEQUAL': 'eve.GEQUAL',
    'EQUAL': 'eve.EQUAL',
    'NOTEQUAL': 'eve.NOTEQUAL',
    'ALWAYS': 'eve.ALWAYS',

    'ARGB1555': 'eve.ARGB1555',
    'L1': 'eve.L1',
    'L4': 'eve.L4',
    'L8': 'eve.L8',
    'RGB332': 'eve.RGB332',
    'ARGB2': 'eve.ARGB2',
    'ARGB4': 'eve.ARGB4',
    'RGB565': 'eve.RGB565',
    'PALETTED': 'eve.PALETTED',
    'TEXT8X8': 'eve.TEXT8X8',
    'TEXTVGA': 'eve.TEXTVGA',
    'BARGRAPH': 'eve.BARGRAPH',
    'PALETTED565': 'eve.PALETTED565',
    'PALETTED4444': 'eve.PALETTED4444',
    'PALETTED8': 'eve.PALETTED8',
    'L2': 'eve.L2',

    'GLFORMAT': 'eve.GLFORMAT',
    'COMPRESSED_RGBA_ASTC_4x4_KHR': 'eve.ASTC_4x4',
    'COMPRESSED_RGBA_ASTC_5x4_KHR': 'eve.ASTC_5x4',
    'COMPRESSED_RGBA_ASTC_5x5_KHR': 'eve.ASTC_5x5',
    'COMPRESSED_RGBA_ASTC_6x5_KHR': 'eve.ASTC_6x5',
    'COMPRESSED_RGBA_ASTC_6x6_KHR': 'eve.ASTC_6x6',
    'COMPRESSED_RGBA_ASTC_8x5_KHR': 'eve.ASTC_8x5',
    'COMPRESSED_RGBA_ASTC_8x6_KHR': 'eve.ASTC_8x6',
    'COMPRESSED_RGBA_ASTC_8x8_KHR': 'eve.ASTC_8x8',
    'COMPRESSED_RGBA_ASTC_10x5_KHR': 'eve.ASTC_10x5',
    'COMPRESSED_RGBA_ASTC_10x6_KHR': 'eve.ASTC_10x6',
    'COMPRESSED_RGBA_ASTC_10x8_KHR': 'eve.ASTC_10x8',
    'COMPRESSED_RGBA_ASTC_10x10_KHR': 'eve.ASTC_10x10',
    'COMPRESSED_RGBA_ASTC_12x10_KHR': 'eve.ASTC_12x10',
    'COMPRESSED_RGBA_ASTC_12x12_KHR': 'eve.ASTC_12x12',


    'NEAREST': 'eve.NEAREST',
    'BILINEAR': 'eve.BILINEAR',

    'BORDER': 'eve.BORDER',
    'REPEAT': 'eve.REPEAT',

    'KEEP': 'eve.KEEP',
    'REPLACE': 'eve.REPLACE',
    'INCR': 'eve.INCR',
    'DECR': 'eve.DECR',
    'INVERT': 'eve.INVERT',

    'DLSWAP_DONE': 'eve.DLSWAP_DONE',
    'DLSWAP_LINE': 'eve.DLSWAP_LINE',
    'DLSWAP_FRAME': 'eve.DLSWAP_FRAME',

    'INT_SWAP': 'eve.INT_SWAP',
    'INT_TOUCH': 'eve.INT_TOUCH',
    'INT_TAG': 'eve.INT_TAG',
    'INT_SOUND': 'eve.INT_SOUND',
    'INT_PLAYBACK': 'eve.INT_PLAYBACK',
    'INT_CMDEMPTY': 'eve.INT_CMDEMPTY',
    'INT_CMDFLAG': 'eve.INT_CMDFLAG',
    'INT_CONVCOMPLETE': 'eve.INT_CONVCOMPLETE',

    'TOUCHMODE_OFF': 'eve.TOUCHMODE_OFF',
    'TOUCHMODE_ONESHOT': 'eve.TOUCHMODE_ONESHOT',
    'TOUCHMODE_FRAME': 'eve.TOUCHMODE_FRAME',
    'TOUCHMODE_CONTINUOUS': 'eve.TOUCHMODE_CONTINUOUS',

    'ZERO': 'eve.ZERO',
    'ONE': 'eve.ONE',
    'SRC_ALPHA': 'eve.SRC_ALPHA',
    'DST_ALPHA': 'eve.DST_ALPHA',
    'ONE_MINUS_SRC_ALPHA': 'eve.ONE_MINUS_SRC_ALPHA',
    'ONE_MINUS_DST_ALPHA': 'eve.ONE_MINUS_DST_ALPHA',

    'BITMAPS': 'eve.BITMAPS',
    'POINTS': 'eve.POINTS',
    'LINES': 'eve.LINES',
    'LINE_STRIP': 'eve.LINE_STRIP',
    'EDGE_STRIP_R': 'eve.EDGE_STRIP_R',
    'EDGE_STRIP_L': 'eve.EDGE_STRIP_L',
    'EDGE_STRIP_A': 'eve.EDGE_STRIP_A',
    'EDGE_STRIP_B': 'eve.EDGE_STRIP_B',
    'RECTS': 'eve.RECTS',

    'OPT_MONO': 'eve.OPT_MONO',
    'OPT_NODL': 'eve.OPT_NODL',
    'OPT_FLAT': 'eve.OPT_FLAT',
    'OPT_CENTERX': 'eve.OPT_CENTERX',
    'OPT_CENTERY': 'eve.OPT_CENTERY',
    'OPT_CENTER': 'eve.OPT_CENTER',
    'OPT_NOBACK': 'eve.OPT_NOBACK',
    'OPT_NOTICKS': 'eve.OPT_NOTICKS',
    'OPT_NOHM': 'eve.OPT_NOHM',
    'OPT_NOPOINTER': 'eve.OPT_NOPOINTER',
    'OPT_NOSECS': 'eve.OPT_NOSECS',
    'OPT_NOHANDS': 'eve.OPT_NOHANDS',
    'OPT_RIGHTX': 'eve.OPT_RIGHTX',
    'OPT_SIGNED': 'eve.OPT_SIGNED',

    'OPT_FULLSCREEN': 'eve.OPT_FULLSCREEN',
    'OPT_MEDIAFIFO': 'eve.OPT_MEDIAFIFO',
    'OPT_FORMAT': 'eve.OPT_FORMAT',
    'OPT_FILL': 'eve.OPT_FILL',

    'LINEAR_SAMPLES': 'eve.LINEAR_SAMPLES',
    'ULAW_SAMPLES': 'eve.ULAW_SAMPLES',
    'ADPCM_SAMPLES': 'eve.ADPCM_SAMPLES',

    'HARP': 'eve.HARP',
    'XYLOPHONE': 'eve.XYLOPHONE',
    'TUBA': 'eve.TUBA',
    'GLOCKENSPIEL': 'eve.GLOCKENSPIEL',
    'ORGAN': 'eve.ORGAN',
    'TRUMPET': 'eve.TRUMPET',
    'PIANO': 'eve.PIANO',
    'CHIMES': 'eve.CHIMES',
    'MUSICBOX': 'eve.MUSICBOX',
    'BELL': 'eve.BELL',
    'CLICK': 'eve.CLICK',
    'SWITCH': 'eve.SWITCH',
    'COWBELL': 'eve.COWBELL',
    'NOTCH': 'eve.NOTCH',
    'HIHAT': 'eve.HIHAT',
    'KICKDRUM': 'eve.KICKDRUM',
    'POP': 'eve.POP',
    'CLACK': 'eve.CLACK',
    'CHACK': 'eve.CHACK',
    'MUTE': 'eve.MUTE',
    'UNMUTE': 'eve.UNMUTE',

    'RAM_G': 'eve.RAM_G',
    'RAM_CMD': 'eve.RAM_CMD',
    'RAM_DL': 'eve.RAM_DL',
    'REG_CLOCK': 'eve.REG_CLOCK',
    'REG_CMDB_SPACE': 'eve.REG_CMDB_SPACE',
    'REG_CMDB_WRITE': 'eve.REG_CMDB_WRITE',
    'REG_CMD_DL': 'eve.REG_CMD_DL',
    'REG_CMD_READ': 'eve.REG_CMD_READ',
    'REG_CMD_WRITE': 'eve.REG_CMD_WRITE',
    'REG_CPURESET': 'eve.REG_CPURESET',
    'REG_TOUCH_CONFIG': 'eve.REG_TOUCH_CONFIG',
    'REG_CSPREAD': 'eve.REG_CSPREAD',
    'REG_DITHER': 'eve.REG_DITHER',
    'REG_DLSWAP': 'eve.REG_DLSWAP',
    'REG_FRAMES': 'eve.REG_FRAMES',
    'REG_FREQUENCY': 'eve.REG_FREQUENCY',
    'REG_GPIO': 'eve.REG_GPIO',
    'REG_GPIO_DIR': 'eve.REG_GPIO_DIR',
    'REG_HCYCLE': 'eve.REG_HCYCLE',
    'REG_HOFFSET': 'eve.REG_HOFFSET',
    'REG_HSIZE': 'eve.REG_HSIZE',
    'REG_HSYNC0': 'eve.REG_HSYNC0',
    'REG_HSYNC1': 'eve.REG_HSYNC1',
    'REG_ID': 'eve.REG_ID',
    'REG_INT_EN': 'eve.REG_INT_EN',
    'REG_INT_FLAGS': 'eve.REG_INT_FLAGS',
    'REG_INT_MASK': 'eve.REG_INT_MASK',
    'REG_MACRO_0': 'eve.REG_MACRO_0',
    'REG_MACRO_1': 'eve.REG_MACRO_1',
    'REG_OUTBITS': 'eve.REG_OUTBITS',
    'REG_PCLK': 'eve.REG_PCLK',
    'REG_PCLK_POL': 'eve.REG_PCLK_POL',
    'REG_PLAY': 'eve.REG_PLAY',
    'REG_PLAYBACK_FORMAT': 'eve.REG_PLAYBACK_FORMAT',
    'REG_PLAYBACK_FREQ': 'eve.REG_PLAYBACK_FREQ',
    'REG_PLAYBACK_LENGTH': 'eve.REG_PLAYBACK_LENGTH',
    'REG_PLAYBACK_LOOP': 'eve.REG_PLAYBACK_LOOP',
    'REG_PLAYBACK_PLAY': 'eve.REG_PLAYBACK_PLAY',
    'REG_PLAYBACK_READPTR': 'eve.REG_PLAYBACK_READPTR',
    'REG_PLAYBACK_START': 'eve.REG_PLAYBACK_START',
    'REG_PWM_DUTY': 'eve.REG_PWM_DUTY',
    'REG_PWM_HZ': 'eve.REG_PWM_HZ',
    'REG_ROTATE': 'eve.REG_ROTATE',
    'REG_SOUND': 'eve.REG_SOUND',
    'REG_SWIZZLE': 'eve.REG_SWIZZLE',
    'REG_TAG': 'eve.REG_TAG',
    'REG_TAG_X': 'eve.REG_TAG_X',
    'REG_TAG_Y': 'eve.REG_TAG_Y',
    'REG_TAP_CRC': 'eve.REG_TAP_CRC',
    'REG_TOUCH_ADC_MODE': 'eve.REG_TOUCH_ADC_MODE',
    'REG_TOUCH_CHARGE': 'eve.REG_TOUCH_CHARGE',
    'REG_TOUCH_DIRECT_XY': 'eve.REG_TOUCH_DIRECT_XY',
    'REG_TOUCH_DIRECT_Z1Z2': 'eve.REG_TOUCH_DIRECT_Z1Z2',
    'REG_TOUCH_MODE': 'eve.REG_TOUCH_MODE',
    'REG_TOUCH_OVERSAMPLE': 'eve.REG_TOUCH_OVERSAMPLE',
    'REG_TOUCH_RAW_XY': 'eve.REG_TOUCH_RAW_XY',
    'REG_TOUCH_RZ': 'eve.REG_TOUCH_RZ',
    'REG_TOUCH_RZTHRESH': 'eve.REG_TOUCH_RZTHRESH',
    'REG_TOUCH_SCREEN_XY': 'eve.REG_TOUCH_SCREEN_XY',
    'REG_TOUCH_SETTLE': 'eve.REG_TOUCH_SETTLE',
    'REG_TOUCH_TAG': 'eve.REG_TOUCH_TAG',
    'REG_TOUCH_TAG_XY': 'eve.REG_TOUCH_TAG_XY',
    'REG_TOUCH_TRANSFORM_A': 'eve.REG_TOUCH_TRANSFORM_A',
    'REG_TOUCH_TRANSFORM_B': 'eve.REG_TOUCH_TRANSFORM_B',
    'REG_TOUCH_TRANSFORM_C': 'eve.REG_TOUCH_TRANSFORM_C',
    'REG_TOUCH_TRANSFORM_D': 'eve.REG_TOUCH_TRANSFORM_D',
    'REG_TOUCH_TRANSFORM_E': 'eve.REG_TOUCH_TRANSFORM_E',
    'REG_TOUCH_TRANSFORM_F': 'eve.REG_TOUCH_TRANSFORM_F',
    'REG_TRACKER': 'eve.REG_TRACKER',
    'REG_TRIM': 'eve.REG_TRIM',
    'REG_VCYCLE': 'eve.REG_VCYCLE',
    'REG_VOFFSET': 'eve.REG_VOFFSET',
    'REG_VOL_PB': 'eve.REG_VOL_PB',
    'REG_VOL_SOUND': 'eve.REG_VOL_SOUND',
    'REG_VSIZE': 'eve.REG_VSIZE',
    'REG_VSYNC0': 'eve.REG_VSYNC0',
    'REG_VSYNC1': 'eve.REG_VSYNC1',

    'RED': 'eve.RED',
    'GREEN': 'eve.GREEN',
    'BLUE': 'eve.BLUE',
    'ALPHA': 'eve.ALPHA',

    # 810
    'REG_MEDIAFIFO_BASE': 'eve.REG_MEDIAFIFO_BASE',
    'REG_MEDIAFIFO_READ': 'eve.REG_MEDIAFIFO_READ',
    'REG_MEDIAFIFO_SIZE': 'eve.REG_MEDIAFIFO_SIZE',
    'REG_MEDIAFIFO_WRITE': 'eve.REG_MEDIAFIFO_WRITE',
    'REG_GPIOX': 'eve.REG_GPIOX',
    'REG_GPIOX_DIR': 'eve.REG_GPIOX_DIR',

    # 815
    'REG_FLASH_SIZE': 'eve.REG_FLASH_SIZE',
    'REG_FLASH_STATUS': 'eve.REG_FLASH_STATUS',
    'REG_ADAPTIVE_FRAMERATE': 'eve.REG_ADAPTIVE_FRAMERATE',

    # 817
    'REG_PCLK_FREQ': 'eve.REG_PCLK_FREQ',
    'REG_PCLK_2X': 'eve.REG_PCLK_2X'
}

DlMap = {
    'VERTEX2F': 'Vertex2f',
    'VERTEX2II': 'Vertex2i',
    'BITMAP_SOURCE': 'BitmapSource',
    'BITMAP_SOURCE2': 'BitmapSource2',
    'CLEAR_COLOR_RGB': 'ClearColorRGB',
    'TAG': 'Tag',
    'COLOR_RGB': 'ColorRGB',
    'BITMAP_HANDLE': 'BitmapHandle',
    'CELL': 'Cell',
    'BITMAP_LAYOUT': 'BitmapLayout',
    'BITMAP_SIZE': 'BitmapSize',
    'ALPHA_FUNC': 'AlphaFunc',
    'STENCIL_FUNC': 'StencilFunc',
    'BLEND_FUNC': 'BlendFunc',
    'STENCIL_OP': 'StencilOp',
    'POINT_SIZE': 'PointSize',
    'LINE_WIDTH': 'LineWidth',
    'CLEAR_COLOR_A': 'ClearColorA',
    'COLOR_A': 'ColorA',
    'CLEAR_STENCIL': 'ClearStencil',
    'CLEAR_TAG': 'ClearTag',
    'STENCIL_MASK': 'StencilMask',
    'TAG_MASK': 'TagMask',
    'BITMAP_TRANSFORM_A': 'BitmapTransformA',
    'BITMAP_TRANSFORM_B': 'BitmapTransformB',
    'BITMAP_TRANSFORM_C': 'BitmapTransformC',
    'BITMAP_TRANSFORM_D': 'BitmapTransformD',
    'BITMAP_TRANSFORM_E': 'BitmapTransformE',
    'BITMAP_TRANSFORM_F': 'BitmapTransformF',
    'SCISSOR_XY': 'ScissorXY',
    'SCISSOR_SIZE': 'ScissorSize',
    'CALL': 'Call',
    'JUMP': 'Jump',
    'BEGIN': 'Begin',
    'COLOR_MASK': 'ColorMask',
    'CLEAR': 'Clear',
    'VERTEX_FORMAT': 'VertexFormat',
    'BITMAP_LAYOUT_H': 'BitmapLayoutH',
    'BITMAP_SIZE_H': 'BitmapSizeH',
    'PALETTE_SOURCE': 'PaletteSource',
    'VERTEX_TRANSLATE_X': 'VertexTranslateX',
    'VERTEX_TRANSLATE_Y': 'VertexTranslateY',
    'NOP': 'Nop',
    'BITMAP_EXT_FORMAT': 'BitmapExtFormat',
    'BITMAP_SWIZZLE': 'BitmapSwizzle',
    'INT_FRR': 'IntFrr',
    'END': 'End',
    'SAVE_CONTEXT': 'SaveContext',
    'RESTORE_CONTEXT': 'RestoreContext',
    'RETURN': 'Return',
    'MACRO': 'Macro',
    'DISPLAY': 'Display',
}

functionMap = {
    'CMD_APPEND' : 'cmd_append',
    'CMD_BGCOLOR' : 'cmd_bgcolor',
    'CMD_BITMAP_TRANSFORM' : 'cmd_bitmap_transform',
    'CMD_BUTTON' : 'cmd_button',
    'CMD_CALIBRATE' : 'cmd_calibrate',
    'CMD_CLOCK' : 'cmd_clock',
    'CMD_COLDSTART' : 'cmd_coldstart',
    'CMD_CSKETCH' : 'cmd_csketch',
    'CMD_DIAL' : 'cmd_dial',
    'CMD_DLSTART' : 'cmd_dlstart',
    'CMD_FGCOLOR' : 'cmd_fgcolor',
    'CMD_GAUGE' : 'cmd_gauge',
    'CMD_GETMATRIX' : 'cmd_getmatrix',
    'CMD_GETPOINT' : 'cmd_getpoint',
    'CMD_GETPROPS' : 'cmd_getprops',
    'CMD_GETPTR' : 'cmd_getptr',
    'CMD_GRADCOLOR' : 'cmd_gradcolor',
    'CMD_GRADIENT' : 'cmd_gradient',
    'CMD_INFLATE' : 'cmd_inflate',
    'CMD_INTERRUPT' : 'cmd_interrupt',
    'CMD_INT_RAMSHARED' : 'cmd_int_ramshared',
    'CMD_INT_SWLOADIMAGE' : 'cmd_int_swloadimage',
    'CMD_KEYS' : 'cmd_keys',
    'CMD_LOADIDENTITY' : 'cmd_loadidentity',
    'CMD_LOADIMAGE' : 'cmd_loadimage',
    'CMD_LOGO' : 'cmd_logo',
    'CMD_MEDIAFIFO' : 'cmd_mediafifo',
    'CMD_MEMCPY' : 'cmd_memcpy',
    'CMD_MEMCRC' : 'cmd_memcrc',
    'CMD_MEMSET' : 'cmd_memset',
    'CMD_MEMWRITE' : 'cmd_memwrite',
    'CMD_MEMZERO' : 'cmd_memzero',
    'CMD_NUMBER' : 'cmd_number',
    'CMD_PLAYVIDEO' : 'cmd_playvideo',
    'CMD_PROGRESS' : 'cmd_progress',
    'CMD_REGREAD' : 'cmd_regread',
    'CMD_ROMFONT' : 'cmd_romfont',
    'CMD_ROTATE' : 'cmd_rotate',
    'CMD_SCALE' : 'cmd_scale',
    'CMD_SCREENSAVER' : 'cmd_screensaver',
    'CMD_SCROLLBAR' : 'cmd_scrollbar',
    'CMD_SETBASE' : 'cmd_setbase',
    'CMD_SETBITMAP' : 'cmd_setbitmap',
    'CMD_SETFONT' : 'cmd_setfont',
    'CMD_SETFONT2' : 'cmd_setfont2',
    'CMD_SETMATRIX' : 'cmd_setmatrix',
    'CMD_SETROTATE' : 'cmd_setrotate',
    'CMD_SETSCRATCH' : 'cmd_setscratch',
    'CMD_SKETCH' : 'cmd_sketch',
    'CMD_SLIDER' : 'cmd_slider',
    'CMD_SNAPSHOT' : 'cmd_snapshot',
    'CMD_SNAPSHOT2' : 'cmd_snapshot2',
    'CMD_SPINNER' : 'cmd_spinner',
    'CMD_STOP' : 'cmd_stop',
    'CMD_SWAP' : 'cmd_swap',
    'CMD_SYNC' : 'cmd_sync',
    'CMD_TEXT' : 'cmd_text',
    'CMD_TOGGLE' : 'cmd_toggle',
    'CMD_TRACK' : 'cmd_track',
    'CMD_TRANSLATE' : 'cmd_translate',
    'CMD_VIDEOFRAME' : 'cmd_videoframe',
    'CMD_VIDEOSTART' : 'cmd_videostart',
    'CMD_FLASHERASE' : 'cmd_flasherase',
    'CMD_FLASHWRITE' : 'cmd_flashwrite',
    'CMD_FLASHREAD' : 'cmd_flashread',
    'CMD_FLASHUPDATE' : 'cmd_flashupdate',
    'CMD_FLASHDETACH' : 'cmd_flashdetach',
    'CMD_FLASHATTACH' : 'cmd_flashattach',
    'CMD_FLASHFAST' : 'cmd_flashfast',
    'CMD_FLASHSPIDESEL' : 'cmd_flashspidesel',
    'CMD_FLASHSPITX' : 'cmd_flashspitx',
    'CMD_FLASHSPIRX' : 'cmd_flashspirx',
    'CMD_FLASHSOURCE' : 'cmd_flashsource',
    'CMD_CLEARCACHE' : 'cmd_clearcache',
    'CMD_INFLATE2' : 'cmd_inflate2',
    'CMD_ROTATEAROUND' : 'cmd_rotatearound',
    'CMD_RESETFONTS' : 'cmd_resetfonts',
    'CMD_ANIMSTART' : 'cmd_animstart',
    'CMD_ANIMSTOP' : 'cmd_animstop',
    'CMD_ANIMXY' : 'cmd_animxy',
    'CMD_ANIMDRAW' : 'cmd_animdraw',
    'CMD_GRADIENTA' : 'cmd_gradienta',
    'CMD_FILLWIDTH' : 'cmd_fillwidth',
    'CMD_APPENDF' : 'cmd_appendf',
    'CMD_ANIMFRAME' : 'cmd_animframe',
    'CMD_NOP' : 'cmd_nop',
    'CMD_SHA1' : 'cmd_sha1',
    'CMD_VIDEOSTARTF' : 'cmd_videostartf',
    'CMD_BITMAP_TRANSFORM' : 'cmd_bitmap_transform'
}